### ISSUE TITLE
Kibana problem

### ISSUE THREAD

**Issue by mfoerstner** [weslambert/velocistack#12]
Hi Wes, I have installed the latest version of Velocistack and I can't open Kibana. It always comes the same message "Kibana Server is not ready yet".

**Comment by weslambert** [comment]
Thanks for testing! I'll have a look at it as I get some time today and get back with you.

**Comment by weslambert** [comment]
Sorry for the delay! I just ran the installer and didn't experience any issue(s) with any of the services coming up. What kind of hardware/specs do you have available?

**Comment by mfoerstner** [comment]
No problem, I use a LXC container with 32 GB RAM, 4 cores and 128 GB disk volume on a Proxmox server. The operating system is Ubuntu 22.04.1 LTS.

**Comment by weslambert** [comment]
If you check the Elasticsearch logs, do you see any issues there?

**Comment by weslambert** [comment]
Please re-open this issue if you still have problems.
