### ISSUE TITLE
Ubuntu 20.04 - Installation Error

### ISSUE THREAD

**Issue by Shad0wCell** [weslambert/velocistack#15]
Hi,

Upon trying to install, I get the following errors:

- [compile-image 6/6] RUN pip3 install -r requirements.txt:                                                                                         
- WARNING: Requirement 'dependencies/docx_generator-0.8.0-py3-none-any.whl' looks like a filename, but the file does not exist                
- WARNING: Requirement 'dependencies/iris_interface-1.2.0-py3-none-any.whl' looks like a filename, but the file does not exist                
- WARNING: Requirement 'dependencies/iris_evtx-1.2.0-py3-none-any.whl' looks like a filename, but the file does not exist                     
- WARNING: Requirement 'dependencies/iris_check_module-1.0.1-py3-none-any.whl' looks like a filename, but the file does not exist             
- WARNING: Requirement 'dependencies/iris_vt_module-1.2.0-py3-none-any.whl' looks like a filename, but the file does not exist
- WARNING: Requirement 'dependencies/iris_misp_module-1.2.0-py3-none-any.whl' looks like a filename, but the file does not exist
- WARNING: Requirement 'dependencies/iris_webhooks_module-1.0.2-py3-none-any.whl' looks like a filename, but the file does not exist
- WARNING: Requirement 'dependencies/iris_intelowl_module-0.1.0-py3-none-any.whl' looks like a filename, but the file does not exist
- Processing /dependencies/docx_generator-0.8.0-py3-none-any.whl
- ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/dependencies/docx_generator-0.8.0-py3-none-any.whl'

When I check the /sources/dependancies/ folder, I see the following files, which don't seem to fall in line

- DFIR-IRIS_pkey.asc
- docx_generator-0.7.0-py3-none-any.whl
- evtx2splunk-2.0.1-py3-none-any.whl
- evtxdump_binaries
- iris_check_module-0.1-py3-none-any.whl
- iris_evtx-1.1-py3-none-any.whl
- iris_interface-1.1-py3-none-any.whl
- iris_ioc_velo_module-0.1.0-py3-none-any.whl
- iris_misp_module-0.1-py3-none-any.whl
- iris_vt_module-0.2-py3-none-any.whl

**Comment by weslambert** [comment]
Hi! Yes, I believe I forgot to copy those over. I should have things updated in the next day or so. Thanks!

**Comment by Shad0wCell** [comment]
Awesome, thanks for the top work. 🙏

**Comment by Shad0wCell** [comment]
Hi, after noticing some changes in the repo, I thought i'd try again.

This time its stuck with the following error

`[+] Building 0.0s (0/0)`

**Comment by weslambert** [comment]
It was late when I pushed the previous changes, so I missed a couple of things. Please try again with the most recent changes.

**Comment by Shad0wCell** [comment]
Worked like a charm :-) Thanks Wes!
