### ISSUE TITLE
Is there any option to add all the services on an existing Velocirapor deployed on GCP? 

### ISSUE THREAD

**Issue by OsMaster** [weslambert/velocistack#6]
Please your advice?

**Comment by weslambert** [comment]
Hi, this is not currently possible, but could be something that we look into for the future (installing alongside an existing Velociraptor installation).

**Comment by weslambert** [comment]
I've added a generic issue (https://github.com/weslambert/velocistack/issues/9) to track this kind of option in the future. We will consider it, but I can't guarantee that anything similra will be available soon. Thanks!
